global_mmlu_lite = [
    "global_mmlu_ar",
    "global_mmlu_bn",
    "global_mmlu_de",
    "global_mmlu_en",
    "global_mmlu_fr",
    "global_mmlu_hi",
    "global_mmlu_id",
    "global_mmlu_it",
    "global_mmlu_ja",
    "global_mmlu_ko",
    "global_mmlu_pt",
    "global_mmlu_es",
    "global_mmlu_sw",
    "global_mmlu_yo",
    "global_mmlu_zh",
]  # global_mmlu_lite
include = [
    "include_base_44_albanian",
    "include_base_44_arabic",
    "include_base_44_armenian",
    "include_base_44_azerbaijani",
    "include_base_44_basque",
    "include_base_44_belarusian",
    "include_base_44_bengali",
    "include_base_44_bulgarian",
    "include_base_44_chinese",
    "include_base_44_croatian",
    "include_base_44_dutch",
    "include_base_44_estonian",
    "include_base_44_finnish",
    "include_base_44_french",
    "include_base_44_georgian",
    "include_base_44_german",
    "include_base_44_greek",
    "include_base_44_hebrew",
    "include_base_44_hindi",
    "include_base_44_hungarian",
    "include_base_44_indonesian",
    "include_base_44_italian",
    "include_base_44_japanese",
    "include_base_44_kazakh",
    "include_base_44_korean",
    "include_base_44_lithuanian",
    "include_base_44_malay",
    "include_base_44_malayalam",
    "include_base_44_nepali",
    "include_base_44_north macedonian",
    "include_base_44_persian",
    "include_base_44_polish",
    "include_base_44_portuguese",
    "include_base_44_russian",
    "include_base_44_serbian",
    "include_base_44_spanish",
    "include_base_44_tagalog",
    "include_base_44_tamil",
    "include_base_44_telugu",
    "include_base_44_turkish",
    "include_base_44_ukrainian",
    # "include_base_44_urdu",
    "include_base_44_uzbek",
    "include_base_44_vietnamese",
]  # Albanian, Arabic, Armenian, Azerbaijani, Basque, Belarusian, Bengali, Bulgarian, Chinese, Croatian, Dutch, Estonian, Finnish, French, Georgian, German, Greek, Hebrew, Hindi, Hungarian, Indonesia, Italian, Japanese, Kazakh, Korean, Lithuanian, Malay, Malayalam, Nepali, North Macedonian, Persian, Polish, Portuguese, russian, Serbian, Spanish, Tagalog, Tamil, Telugu, Turkish, Ukrainian, Urdu, Uzbek, Vietnamese
arc = [
    "arc_ar",
    "arc_bn",
    "arc_ca",
    "arc_da",
    "arc_de",
    "arc_es",
    "arc_eu",
    "arc_fr",
    "arc_gu",
    "arc_hi",
    "arc_hr",
    "arc_hu",
    "arc_hy",
    "arc_id",
    "arc_it",
    "arc_kn",
    "arc_ml",
    "arc_mr",
    "arc_ne",
    "arc_nl",
    "arc_pt",
    "arc_ro",
    "arc_ru",
    "arc_sk",
    "arc_sr",
    "arc_sv",
    "arc_ta",
    "arc_te",
    "arc_uk",
    "arc_vi",
    "arc_zh",
]  # arc_{ar,bn,ca,da,de,es,eu,fr,gu,hi,hr,hu,hy,id,it,kn,ml,mr,ne,nl,pt,ro,ru,sk,sr,sv,ta,te,uk,vi,zh}
mgsm = ["mgsm_cot_native"]
